### ISSUE TITLE
Track multiple Retrieval Peers

### ISSUE THREAD

**Issue by hannahhoward** [filecoin-project/go-fil-markets#101]
When I store the same piece twice, I should track all miners I've stored it with so I can retrieve from all those miners.

See: https://github.com/filecoin-project/go-fil-markets/blob/master/retrievalmarket/discovery/local.go#L25

Scope:
- local discovery cache is currently pieceCid -> retrievalPeer
- probably want to make it pieceCid -> retrievalPeerList
where retrievalPeerList =
type retrievalPeerList struct {
peers []retrievalPeer
}
(make sure to cbor gen with cbor-gen-for)
- make sure to read current value and check for uniqueness before appending to list

**Comment by jsign** [comment]
This would be nice to support use-cases in which a Piece is stored in multiple miners for replication.
