### ISSUE TITLE
Proposal: Making Robust Node Interfaces To Handle Chain Events

### ISSUE THREAD

**Issue by hannahhoward** [filecoin-project/go-fil-markets#224]
# Background

This proposal outlines two options for more robust interfaces between the markets and the node implementations. It aims to solve most of the challenges outlined in this issue: https://github.com/filecoin-project/specs/issues/919. Please familiarize yourself with that before reading this proposal.

# Principles

1. Don't wait on chain messages by message CID
1. API's that submit a message to the chain do not return a message cid, and do not wait for the message to appear on chain. At most the APIs return the Nonce value for the submitted message.
1. Logic that is unique to the markets module should live in the markets module, logic that could be shared and used by other shared modules should live in the node or a separate module outside of markets
1. Per https://github.com/filecoin-project/specs/issues/919 -- we must always account for: 
     1. messages we expect to appear on chain never do
     1. we should wait for a confidence level before doing anything
     1. even after we reach a certain confidence level, we still need to handle the possibility of a revert

# Current Interfaces

[Common Storage Node Interfaces](https://github.com/filecoin-project/go-fil-markets/blob/master/storagemarket/types.go#L349)
[Storage Client Node Interface](https://github.com/filecoin-project/go-fil-markets/blob/master/storagemarket/types.go#L394) 
[Storage Provider Node Interface](https://github.com/filecoin-project/go-fil-markets/blob/master/storagemarket/types.go#L368) 
[Retrieval Client Node Interface](https://github.com/filecoin-project/go-fil-markets/blob/master/retrievalmarket/types.go#L195) 
[Retrieval Provider Node Interface](https://github.com/filecoin-project/go-fil-markets/blob/master/retrievalmarket/types.go#L342)

# Option A: Semantic API

In this first proposal, the node interface provides query methods, methods to submit messages to chain, and semantic methods to wait for specific things to happen. The waiting functions all take into account confidence and timeouts, and must supply a function to handle reverts later after the event was already assumed to have happened.

```golang

type WaitParams struct {
  // Confidence is the number of epochs to wait after the message is applied
  // before we inspect it's return
  Confidence abi.ChainEpoch   
  // Timeout is the epoch at which we'll consider this submission to have failed
  Timeout abi.ChainEpoch
  // OnRevertAfterApply is called when the tipset that triggered success on the
  // event we're waiting for was dropped, after the confidence interval has
  // passed. Tsc is a token for the tipset that was dropped
  OnRevertAfterApply func(ctx, tsc shared.TipsetToken) error
}

type NodeCommon interface {
  GetChainHead(ctx context.Context) (shared.TipSetToken, abi.ChainEpoch, error)
}

type DealSectorCommittedCallback func(err error)
type WaitForBalanceCallback func(err error)
type DealsPublishedCallback func(abi.DealID, err error)

type MessageNonce uint64

type StorageCommon interface {
  NodeCommon

  // Adds funds with the StorageMinerActor for a storage participant.  Used by
  // both providers and clients.
  AddFunds(ctx context.Context, addr address.Address, amount abi.TokenAmount) 
  error

  // Ensures that a storage market participant has a certain amount of available
  // funds If additional funds are needed, they will be sent from the 'wallet'
  // address callback is immediately called if sufficient funds are available
  EnsureFunds(ctx context.Context, addr, wallet address.Address, 
    amount abi.TokenAmount, tok shared.TipSetToken) error

  // GetBalance returns locked/unlocked for a storage participant.  Used by both
  // providers and clients.
  GetBalance(ctx context.Context, addr address.Address, 
    tok shared.TipSetToken) (Balance, error)

  WaitForBalance(ctx context.Context, addr, wallet address.Adress, 
    amount Abi.TokenAmount, cb WaitForBalanceCallback, 
   waitParams WaitParams)

  // Verify a signature against an address + data
  VerifySignature(ctx context.Context, signature crypto.Signature, 
    signer address.Address, plaintext []byte, tok shared.TipSetToken) 
    (bool, error)

  // ValidatePublishedDeal verifies and attempt to publisha  specific
  // ClientDealProposal was successful
  ValidatePublishedDeal(ctx context.Context, deal samarket.ClientDealProposal, publishMessageNonce MessageNonce, cb DealsPublishedCallback, waitParams WaitParams) error

  // OnDealSectorCommitted verifies that a deal's piece was committed to a
  // sector
  OnDealSectorCommitted(ctx context.Context, provider address.Address, 
    dealID abi.DealID, cb DealSectorCommittedCallback, waitParams WaitParams) 
    error

}

// Node dependencies for a StorageClient
type StorageClientNode interface {
  StorageCommon

  // ListClientDeals lists all on-chain deals associated with a storage client
  ListClientDeals(ctx context.Context, addr address.Address, 
    tok shared.TipSetToken) ([]StorageDeal, error)

  // GetStorageProviders returns information about known miners
  ListStorageProviders(ctx context.Context, tok shared.TipSetToken) 
  ([]*StorageProviderInfo, error)

  // SignProposal signs a proposal
  SignProposal(ctx context.Context, signer address.Address, 
    proposal market.DealProposal) (*market.ClientDealProposal, error)

  GetDefaultWalletAddress(ctx context.Context) (address.Address, error)

  ValidateAskSignature(ctx context.Context, ask *SignedStorageAsk, 
    tok shared.TipSetToken) (bool, error)

}

// Node dependencies for a StorageProvider
type StorageProviderNode interface {
  StorageCommon

  // Publishes deal on chain, returns the message cid, but does not wait for
  // message to appear
  PublishDeals(ctx context.Context, deal MinerDeal) (MessageNonce, error)

  // ListProviderDeals lists all deals associated with a storage provider
  ListProviderDeals(ctx context.Context, addr address.Address, 
    tok shared.TipSetToken) ([]StorageDeal, error)

  // Called when a deal is complete and on chain, and data has been transferred
  // and is ready to be added to a sector
  OnDealComplete(ctx context.Context, deal MinerDeal, pieceSize 
    abi.UnpaddedPieceSize, pieceReader io.Reader) error

  // returns the worker address associated with a miner
  GetMinerWorkerAddress(ctx context.Context, addr address.Address, tok 
    shared.TipSetToken) (address.Address, error)

  // Signs bytes
  SignBytes(ctx context.Context, signer address.Address, b []byte) 
  (*crypto.Signature, error)

  LocatePieceForDealWithinSector(ctx context.Context, dealID abi.DealID, 
    tok shared.TipSetToken) 
    (sectorID uint64, offset uint64, length uint64, err error)
}

type WaitForPaymentChannelFundsCallback func(address.address, error)

// RetrievalClientNode are the node dependencies for a RetrievalClient
type RetrievalClientNode interface {
  NodeCommon

  // GetOrCreatePaymentChannel sets up a new payment channel if one does not
  // exist between a client and a miner and insures the client has the given
  // amount of funds available in the channel
  GetOrCreatePaymentChannel(ctx context.Context, clientAddress address.Address,
     minerAddress address.Address, clientFundsAvailable abi.TokenAmount, 
     tok shared.TipSetToken) error

  // Allocate late creates a lane within a payment channel so that calls to
  // CreatePaymentVoucher will automatically make vouchers only for the
  // difference in total
  AllocateLane(paymentChannel address.Address) (uint64, error)

  // CreatePaymentVoucher creates a new payment voucher in the given lane for a
  // given payment channel so that all the payment vouchers in the lane add up
  // to the given amount (so the payment voucher will be for the difference)
  CreatePaymentVoucher(ctx context.Context, paymentChannel address.Address, 
    amount abi.TokenAmount, lane uint64, tok shared.TipSetToken) 
    (*paych.SignedVoucher, error)

  // WaitForPaymentChannelFunds waits for a message on chain that funds have
  // been sent to a payment channel
  WaitForPaymentChannelFunds(ctx context.Context, clientAddress address.Address, 
    minerAddress address.Address, clientFundsAvailable abi.TokenAmount, 
    cb WaitForPaymentChannelFundsCallback, waitParams WaitParams)
}

// RetrievalProviderNode are the node depedencies for a RetrevalProvider
type RetrievalProviderNode interface {
       NodeCommon
  // returns the worker address associated with a miner
  GetMinerWorkerAddress(ctx context.Context, miner address.Address,
     tok shared.TipSetToken) (address.Address, error)
  UnsealSector(ctx context.Context, sectorID uint64, offset uint64, 
    length uint64) (io.ReadCloser, error)
  SavePaymentVoucher(ctx context.Context, paymentChannel address.Address, 
    voucher *paych.SignedVoucher, proof []byte, expectedAmount abi.TokenAmount,
    tok shared.TipSetToken) (abi.TokenAmount, error)
}
```

Advantages: Easier to understand, easier to write the markets module, more freedom for node implementors in terms of how they implement waiting (by message? by state change? we don't need to know), less forced shared types Disadvantages: Potentially more brittle, more work happens in the adapters on the node side, more apis

# Option B: Generic Waiting Method

In this proposal, the node interface provides query methods, methods to submit messages to chain, and a generic wait for message method, not based on message CID and accounting for confidence, timeouts, and reverts

The message waiting function is modelled on Lotus's events API, with a few simplifications

```golang

// MessageParams are the parameters of the message that the markets module may
// want to inspect
type MessageParams struct {
  To   address.Address
  From address.Address
  Nonce MessageNonce
  Method abi.MethodNum
  Params []byte
}

type MessageWaitParams struct {
  // Confidence is the number of epochs to wait after the message is applied
  // before we inspect it's return
  Confidence abi.ChainEpoch   
  // Timeout is the epoch at which we'll consider this submission to have failed
  Timeout abi.ChainEpoch
  // MatchMessage inspects a message that has appeared in a new tipset to
  // determine if it's the message we're waiting for
  MatchMessage func(msg MessageParams) (bool, error)
  // AlreadyHappenedCheck -- already happened is called immediately to determine
  // if the event has already happened in a recent tipset, meaning we can assume
  // there's no need to keep waiting for the event -- useful if it's a message
  // we did not submit ourselves
  AlreadyHappenedCheck func(tsc shared.TipsetToken) (bool, error)
  // OnAppliedAfterConfidence is called when the message has been applied and
  // the corresponding interval has passed without a revert
  OnAppliedWithConfidence func(msg MessageParams, code exitcode.ExitCode, 
    retVal []byte, tsc shared.TipsetToken, curH abi.ChainEpoch) (err error)
  // OnTimedOut is called when the event never happens
  OnTimedOut func(tsc shared.TipsetToken, curH abi.ChainEpoch)
  // OnRevertAfterApply is called when the tipset containing a message is
  // dropped, after the confidence interval has passed. Tsc is a token for the
  // tipset that was dropped
  OnRevertAfterApply func(ctx, tsc shared.TipsetToken) error
}

type NodeCommon interface {
  GetChainHead(ctx context.Context) (shared.TipSetToken, abi.ChainEpoch, error)
  WaitForMessage(ctx context.Context, params MessageWaitParams) error
}
```

The node interfaces then are as follows:

```golang

// StorageDeal is a local combination of a proposal and a current deal state
type StorageDeal struct {
  market.DealProposal
  market.DealState
}

type StorageCommon interface {
  NodeCommon

  // Adds funds with the StorageMinerActor for a storage participant.  Used by
  // both providers and clients.
  AddFunds(ctx context.Context, addr address.Address, amount abi.TokenAmount) 
  error

  // Ensures that a storage market participant has a certain amount of available
  // funds If additional funds are needed, they will be sent from the 'wallet'
  // address callback is immediately called if sufficient funds are available
  EnsureFunds(ctx context.Context, addr, wallet address.Address, 
    amount abi.TokenAmount, tok shared.TipSetToken) error

  // GetBalance returns locked/unlocked for a storage participant.  Used by both
  // providers and clients.
  GetBalance(ctx context.Context, addr address.Address, 
    tok shared.TipSetToken) (Balance, error)

  // Verify a signature against an address + data
  VerifySignature(ctx context.Context, signature crypto.Signature, 
    signer address.Address, plaintext []byte, tok shared.TipSetToken) 
    (bool, error)

  GetStorageDeal(ctx context.Context, dealID abi.DealID, tsc shared.TipSetToken)
    (StorageDeal, error)
}


// Node dependencies for a StorageClient
type StorageClientNode interface {
  StorageCommon

  // ListClientDeals lists all on-chain deals associated with a storage client
  ListClientDeals(ctx context.Context, addr address.Address, 
    tok shared.TipSetToken) ([]StorageDeal, error)

  // GetStorageProviders returns information about known miners
  ListStorageProviders(ctx context.Context, tok shared.TipSetToken) 
  ([]*StorageProviderInfo, error)

  // SignProposal signs a proposal
  SignProposal(ctx context.Context, signer address.Address, 
    proposal market.DealProposal) (*market.ClientDealProposal, error)

  GetDefaultWalletAddress(ctx context.Context) (address.Address, error)

  ValidateAskSignature(ctx context.Context, ask *SignedStorageAsk, 
    tok shared.TipSetToken) (bool, error)
}


// Node dependencies for a StorageProvider
type StorageProviderNode interface {
  StorageCommon

  // Publishes deal on chain, returns the message cid, but does not wait for
  // message to appear
  PublishDeals(ctx context.Context, deal MinerDeal) (MessageNonce, error)

  // ListProviderDeals lists all deals associated with a storage provider
  ListProviderDeals(ctx context.Context, addr address.Address, 
    tok shared.TipSetToken) ([]StorageDeal, error)

  // Called when a deal is complete and on chain, and data has been transferred
  // and is ready to be added to a sector
  OnDealComplete(ctx context.Context, deal MinerDeal, pieceSize 
    abi.UnpaddedPieceSize, pieceReader io.Reader) error

  // returns the worker address associated with a miner
  GetMinerWorkerAddress(ctx context.Context, addr address.Address, 
    tok shared.TipSetToken) (address.Address, error)

  // Signs bytes
  SignBytes(ctx context.Context, signer address.Address, b []byte) 
  (*crypto.Signature, error)

  LocatePieceForDealWithinSector(ctx context.Context, dealID abi.DealID, 
    tok shared.TipSetToken) (sectorID uint64, offset uint64, length uint64, 
      err error)
}

// RetrievalClientNode are the node dependencies for a RetrievalClient
type RetrievalClientNode interface {
  NodeCommon

  // GetOrCreatePaymentChannel sets up a new payment channel if one does not
  // exist between a client and a miner and insures the client has the given
  // amount of funds available in the channel
  GetOrCreatePaymentChannel(ctx context.Context, clientAddress address.Address,
     minerAddress address.Address, clientFundsAvailable abi.TokenAmount, 
     tok shared.TipSetToken) error

  // Allocate late creates a lane within a payment channel so that calls to
  // CreatePaymentVoucher will automatically make vouchers only for the
  // difference in total
  AllocateLane(paymentChannel address.Address) (uint64, error)

  // CreatePaymentVoucher creates a new payment voucher in the given lane for a
  // given payment channel so that all the payment vouchers in the lane add up
  // to the given amount (so the payment voucher will be for the difference)
  CreatePaymentVoucher(ctx context.Context, paymentChannel address.Address, 
    amount abi.TokenAmount, lane uint64, tok shared.TipSetToken) 
    (*paych.SignedVoucher, error)

  // GetPaymentChannel returns a payment channel address for a given client /
  // miner combo
  GetPaymentChannel(clientAddress address.Address, minerAddress address.Address)
   (address.Address, error)
}

// RetrievalProviderNode are the node depedencies for a RetrevalProvider
type RetrievalProviderNode interface {
  NodeCommon
  // returns the worker address associated with a miner
  GetMinerWorkerAddress(ctx context.Context, miner address.Address, 
    tok shared.TipSetToken) (address.Address, error)
  UnsealSector(ctx context.Context, sectorID uint64, offset uint64, 
    length uint64) (io.ReadCloser, error)
  SavePaymentVoucher(ctx context.Context, paymentChannel address.Address, 
    voucher *paych.SignedVoucher, proof []byte, expectedAmount abi.TokenAmount, 
    tok shared.TipSetToken) (abi.TokenAmount, error)
}
```

Advantages: Less methods on node interfaces, less work done inside of node adapter Disadvantages: Events API is complicated! Locked into a specific wait to wait for chain events (messages) and limits nodes ability to implement it's own approach. Have to add additional query methods.

# Other Concerns

### Mainnet/Freeze Approaching

In my opinion, a major overriding concern is that we are approaching mainnet, with several outstanding deliverables, and the current software, while inflexible and probably failure prone, works to makes deals in LOTUS. As such, I think we should consider which path gets us to working software quickest without a lot of work and less risk. My gut intuition is option A meets these criteria more, as most of the methods already exist on the node and just need to have some extra functionality.

### Indexes of chain state

Some pieces of chain state are difficult to locate in places other than the message return value. In these cases, the node may maintain an off-chain index mapping a well-known value to the harder to locate value. Currently, both nodes do this for payment channels (though there are some issues with this index we're still looking at) and it might make sense to do this for proposalCID + MessageNonce -> DealID (technically two deals can have the same proposal cid I think). However, these proposals I believe can both be implemented without this additional index, depending on how the node wants to handle setup.

### RPC API

Something to factor in for all this is the possibility that the markets will be daemonized, and we will need to communicate over an API.

### Observing messages vs state

In option B, the WaitForMessage call is based on the LOTUS events API, which is message based rather than state based. I assume there is a performance component to this, as new messages can be extracted directly from a tipset already in memory? (cc: @whyrusleeping ) Could our WaitForMessage API work with pure state instead? (I believe this would require an additional form of events API in Lotus)

### Whether to return a Nonce on API's that submit messages

I opted for now to only return a Nonce on PublishDeals, because I believe you can identify whether a messages with meet the conditions needed to move forward in cases other than PublishDeals with other parameters of a message (for example, if you're waiting for funds, you're not so much waiting for a specific message as a message that adds the required funds to the existing balance)

**Comment by acruikshank** [comment]
An Option C would be to eliminate the waiting methods altogether and, instead provide wait parameters to any method that requires sending a message that requires a wait. 

There is a race condition where a message lands on chain before the wait is begun. The node should check some number of head tipsets for the message, but in the existing and proposed interfaces, the node can't know far to look back for safety. This is just an example of why message CIDs and wait semantics shouldn't leak across this interface. Also, component code should not be inspecting chain messages.

That said the node shouldn't own the details of __why__ it needs to wait, so the wait parameters do make sense. The proposed interface seems to be providing unnecessary transparency into chain state, though. The component code should only ever need to operate in one of two modes: reversible actions or irreversible actions. The former should learn about the message as soon as it arrives and also learn of every invalidation and reappearance. That is to say it needs to have a confidence interval of zero and should get both message and invalidation event. Irreversible actions should only require a single notification after a confidence interval.

So wait parameters:
``` go
type MessageWaitParams struct {
    // Confidence is the number of epochs to wait after the message is applied before we inspect 
    // it's return
    Confidence abi.ChainEpoch   
    // Timeout is the epoch at which we'll consider this submission to have failed
    Timeout abi.ChainEpoch
    // OnMessageStatus is called when the message status has changed. It will be called
    // with retVal populated If the message lands on chain and confidence interval has passed without the message being invalidated.
    // err may be one of:
    //   ErrMsgInvalidated if the message was on chain and the confidence interval passed, but it was later invalidated
    //   ErrMsgTimeout if the timeout interval has been observed with the message either never landing or having landed and but currently invalidated.
    //   ErrMsgFailure if the message lands on chain at the confidence interval, but was not successfully applied.
    OnMessageStatus func(retVal []byte, tsc shared.TipsetToken, err error)
}
```
Should be sufficient. If it's not, there's probably issues at the protocol level that should be worked out. At the very least, they should be handled with dedicated methods and not baked into the API's data structures.

**Comment by hannahhoward** [comment]
@acruikshank a perhaps unstated concern we would like to record the fact we posted a message before we know that it went through, to avoid attempting to repost, should the module need to restart.

**Comment by anorth** [comment]
I'm not sure what closing of this issue was intended to indicate. Some thoughts.

> Don't wait on chain messages by message CID

My prior unease about message waiting was not primarily concerned about use of a CID as the key, and it seems like a reasonable one. A pair of (sender, nonce) would be another option, but would require then inspecting the state to determine if the right transition had happened. It could detect a different message "stealing" the nonce, though. That nonce-stealing could still be reverted, though, so it's not necessarily safe to re-try non-idempotent operations immediately.

> Logic that is unique to the markets module should live in the markets module, logic that could be shared and used by other shared modules should live in the node or a separate module outside of markets

_Could_ be shared is not a high enough bar for logic living in the node.

> Option A: semantic API

I don't think it's easier to understand, though I guess it depends on your point of view. There's certainly a lot more that needs understanding given the larger API surface area.

I don't think "easier to write the markets module" is a good goal. That module only needs to be written once and is a generally less complex system than a node. But the node will be written 4 or more times. So related to this, I don't think "more freedom for node implementors" is necessarily the right direction either; an extremely tightly defined API would be more beneficial.

The API brittleness and volume of APIs and adapter code is a significant concern.

> Option B

I think this is generally more promising, but still has a large API surface area, about which I will write more elsewhere.

> Option C

I think race conditions would be better handled by observing state. We have more flexibility and smaller node responsibilities if the module side does the waiting explicitly.

> Mainnet/Freeze Approaching

Mainnet need not imply a freeze to these APIs. However, the sooner we improve and stabilise them, the better. We'll pay integration costs for a long time. It is worth investing in getting this right now.

> Indexes of chain state

I think indexes are very likely to be part of solutions here. But unless entirely generic, they should be maintained by the modules rather than the node.

> Observing messages vs state

It seems to be that observing state alone can never be sufficient for a complete solution. This is because we have non-idempotent messages. For example, when transferring value, we must wait for the transfer message to happen or not happen: we can't just observe state each epoch and make another send if the target balance is not yet high enough. If we could also observe message pools, it might get a lot closer.

That said, observing state is much more robust in places where it does work, and I think would make a good primary API.

**Comment by anorth** [comment]
> It seems to be that observing state alone can never be sufficient for a complete solution

Maybe I'm wrong here, and mischaracterised what waiting would look like. We *can* send funds, and then wait for a state predicate about the target balance increasing, before then proceeding with the next step of some process. 
- it might not matter which message made the transfer, so long as the balance is what we need
- we can still time-out and retry
- even if we did message-waiting, we'd still need to re-check the state predicate after the message lands to confirm the balance is what we need, and didn't decrease in the meantime

I'm not sure if there are cases that really can't be expressed as state predicates.
