### ISSUE TITLE
README.md has broken link to CONTRIBUTING.md

### ISSUE THREAD

**Issue by x448** [filecoin-project/go-fil-markets#23]
Clicking on CONTRIBUTING at "please see our CONTRIBUTING guide." returns "Not Found" for the URL:  https://github.com/filecoin-project/go-fil-components/CONTRIBUTING.md

**Comment by shannonwells** [comment]
Thanks.  The repo was renamed and the README link was missed.

**Comment by shannonwells** [comment]
This is actually fixed in master now.  Closing.
