### ISSUE TITLE
Architecture document

### ISSUE THREAD

**Issue by schomatis** [filecoin-project/go-fil-markets#266]
I need architecture documentation or the closest we can get to it here, similar to what's being done in https://github.com/filecoin-project/lotus/pull/1768. In general it should be as self-contained as possible (the spec might not be complete at this point).

Preferably this should be in place by the week of **June 22nd**.

**Comment by hannahhoward** [comment]
Hi @schomatis we just merged a PR to update a bunch of docs. 

Most of these to be clear are aimed at guiding a node implementer who wants to use these modules, and are not focused on the internals how the module works, but it still covers a lot.

Can you take a look at these and let me know what else you need? Also, while out of date, the specs for the markets are actually pretty readable. If they were brought up to date, would that be sufficient?

Also, maybe be worth reviewing how the finite state machine works: https://github.com/filecoin-project/go-statemachine/tree/master/fsm

**Comment by hannahhoward** [comment]
we can definitely provide you what you need by the week in question.

**Comment by schomatis** [comment]
Hi @hannahhoward, the documentation is targeted at security reviews so we need as much as we can get to dive into the internals, will take a look at all of those sources though and provide a more scoped request. Still, I'm flagging this early so you can better plan in advance time allocation for this effort, thanks.

**Comment by schomatis** [comment]
@hannahhoward 

I'm going to start with the positive so everything that follows can be read in that context. First, this code is _much_ better structured and documented than Lotus (we should be ashamed of ourselves), it even has READMEs for every component. The Markets spec is in a much better shape than other sections (still needs to be revised and updated though) and does give a high-level picture to help better form the conceptual model to think through the code which is very helpful.

All that said, none of the above amounts to actual internal architecture documentation, the current documentation is written for the user but not for the developer, understanding how things work in the code is _very_ time consuming at the moment. Additionally, the FSM used makes things much harder for a human to follow, still they seem like the right tool for the job, I'm just highlighting that the aggregated cost of following this declarative programming style is much more expensive than in Lotus, that cost needs to be acknowledged and compensated for in the documentation. The FSM documentation itself tells me how an FSM works but not how it is _used_ internally here, how the different states and statuses are connected together. This is the kind of information needed to efficiently navigate the code, e.g., if I want to check where a specific validation is enforced I shouldn't have to start from the initial state and decipher all the required transitions to get to the function of interest, I should a priori have some knowledge of where the different parts of the logic lie and start the search at a neighbor state or function.

To better illustrate all this I pushed some [notes](https://github.com/filecoin-project/go-fil-markets/pull/271) while reading the code flow for the `lotus client deal` command. Also give a quick look to the Lotus [architecture doc](https://github.com/filecoin-project/lotus/blob/master/documentation/en/architecture.md) to see the type of information I'm referring to. The doc is still not in a good state and that may even further illustrate that I am mostly concerned about content at the moment and not form or style, it is written by engineers with medium to low writing skill (the low is specially true on my end) so you shouldn't need a technical writer to accomplish this (although all of our docs could use writers that actually know what they're doing, but it's not a priority for now).

I acknowledge that we don't have enough time to do a thorough documentation so I would settle with an expanded and cleaned version of the `lotus client deal` flow I already pushed. Let's call that 70-80% of the documentation needed and allow me some margin to request any follow-up information I can think of that could also be useful. Ping me for review, comments, or in any other way I can be of help. Any information you can dump in a doc will be extremely useful at this point, thanks.
