### ISSUE TITLE
Allow custom decider function for retrieval deals

### ISSUE THREAD

**Issue by whyrusleeping** [filecoin-project/go-fil-markets#268]
We recently added the ability to specify a custom deal accepter function to the storage deal flow, we should also add the same thing to the retrieval side.

**Comment by hannahhoward** [comment]
closed by merge of #262

**Comment by whyrusleeping** [comment]
@hannahhoward that PR adds this for the storagemarket, this issue is about the same thing, but for the retrieval side

**Comment by hannahhoward** [comment]
oh sorry!

**Comment by hannahhoward** [comment]
Notes for implemener:

Recommend same approach used for storage market -- but need to add a functional options config pattern to retrieval provider initialization as well.
