### ISSUE TITLE
Refactor: Don't keep any protocol connections open

### ISSUE THREAD

**Issue by hannahhoward** [filecoin-project/go-fil-markets#296]
We should close libp2p streams as quickly as possible generally remove connection maintaining code:

Client Side:
- Put the sending of deal response and waiting for intent to accept in the same state handler (ProposeDeal) on client
- Close connection after receiving intent to accept
- Remove conn manager entirely
- Do not re-establish connections on restart
- Can probably remove the ConnectionClosed attribute from ClientDeal
- Probably need NewQueryStream & NewDealStream methods on ClientDealEnvironment

Provider Side:
- Close connection after intent to accept sent in DecideOnProposal.
- Remove ValidateDealProposal & DecideOnDeal from state machine? Just run directly in Libp2p response (though definitely in their own functions :)?
- This would enable removing: ConnectionClosed attribute from MinerDeal & deleting ConnManager entirely
- Also removes the need to send a deal response in FailDeal
- Remove SendResponse, CloseStream, etc from ProviderDealEnvironment

**Comment by ingar** [comment]
I believe this is fixed with #297
