### ISSUE TITLE
Infinite Accumulation of deals and readers in retrieval markets

### ISSUE THREAD

**Issue by vyzo** [filecoin-project/go-fil-markets#310]
I am adding code to protect the deals and block readers in retrieval market from concurrent modification and fix #301 and I discovered to my dismay that there is no code whatsoever that ever deletes stuff from the `dealStreams` and `blockReaders` maps.
This is a memory leak which will eventually crash the lotus node with OOM if left unchecked.

**Comment by hannahhoward** [comment]
@vyzo the new retrieval market code has been merged and I believe this issue is resolved, as the maps in question are no longer in the code.

I'm closing this for now but feel free to file a seperate issue if you see any other issues with maps not getting cleaned up, let me know :)
