### ISSUE TITLE
Mitigate dialing errors

### ISSUE THREAD

**Issue by hannahhoward** [filecoin-project/go-fil-markets#354]
We seem to be getting a lot of dialing errors / routing not found errors for retrieval/storage deals (particularly retrieval).

We want to mitigate this by taking two steps:
1. In the storage market network, when we add multiaddrs, we set the timeout for only 10 minutes. On larger deals, this could easily drop over the course of the deal.
2. In the retrieval market network, we don't add multiaddrs! Eek. We need to add them.

**Comment by daviddias** [comment]
Thank you for logging this issue, @hannahhoward.

Once this one is fixed, we need to ship a new version of the deal-bot with it.

**Comment by hannahhoward** [comment]
resolved by #356
