### ISSUE TITLE
SPs and clients should be able to mark content as not available for retrieval

### ISSUE THREAD

**Issue by honghaoq** [filecoin-project/go-fil-markets#704]

**Comment by willscott** [comment]
@honghaoq  you initially wrote the title for this issue to indicate you wanted to be able to prevent indexing/retrieval of specific CIDs. Do you know if that's the right granularity, or if providers/clients want to be able to deny retrieval at a deal level?

**Comment by LexLuthr** [comment]
The goal is to deny indexing and not the retrieval itself. If deal is not indexed then only the client who made the deal can still retrieve it.

**Comment by honghaoq** [comment]
The granularity is at deal level! Mayank also flag this to Boost since go-fil-market is deprecating in 2 months.

**Comment by willscott** [comment]
> The goal is to deny indexing and not the retrieval itself. If deal is not indexed then only the client who made the deal can still retrieve it.

just not indexing content doesn't make that content not retrievable.
I'd be very worried about this setting giving providers a false sense of security.

I think a control that is saying 'this is private content, don't index it' needs to also make that content not retrievable, or you're opening yourself up to very easily having providers improperly configure their permissions

**Comment by LexLuthr** [comment]
@willscott But denying retrieval would also deny end client to retrieve data. So they will have to go offline route to get their data from SPs. Wouldn't that create a more complex retrieval process?

**Comment by willscott** [comment]
there can be an over-ride for the specific client, but i guess the point is that content not indexed probably should be 'default-deny' for retrievals

**Comment by honghaoq** [comment]
@LexLuthr just to confirm, will you be following up with Lotus team on this requirement?
On a side note, I wanted to tag your name for this task but looks like I dont have permission to do so, would be great if you can grant me permission to Lotus / gofilmarkets repo, thanks!

**Comment by LexLuthr** [comment]
@honghaoq https://github.com/filecoin-project/lotus/issues/8520 opened. I don't have perms to allow access. You can ask @jennijuju for access to those repos.

**Comment by honghaoq** [comment]
Closed as Duplicate https://github.com/filecoin-project/storetheindex/issues/728
