### ISSUE TITLE
How to output the log of this package in Lotus

### ISSUE THREAD

**Issue by s1mple1122** [filecoin-project/go-fil-markets#742]
DEBUG=true or  log=DEBUG     cant output

**Comment by rvagg** [comment]
See https://github.com/ipfs/go-log/ for detailed instructions. So something like `GOLOG_LOG_LEVEL="storagemrkt=debug"` should do it, but you need to find the specific logger you want, different packages in here have different loggers: https://github.com/filecoin-project/go-fil-markets/search?q=logging.Logger

I hope that helps.
