### ISSUE TITLE
Retrieval checkForActiveDeal is too aggressive

### ISSUE THREAD

**Issue by magik6k** [filecoin-project/go-fil-markets#753]
I'm not sure why exactly we want to stop duplicate retrievals for the same piece, but [checkForActiveDeal](https://github.com/filecoin-project/go-fil-markets/blob/1b2548cf4cf1bb0f90a779b92673a98a1a1c2003/retrievalmarket/impl/client.go#L312) should at least permit retrievals for the same piece with different selectors.

Being able to only do a single retrieval per piece in parallel severely limits tools like https://github.com/filecoin-project/lotus/pull/9382.

**Comment by dirkmc** [comment]
Looks like it was implemented as a requirement of https://github.com/filecoin-project/lotus/issues/5443

I agree though, there's not really a good reason to prevent multiple concurrent deals.

**Comment by hannahhoward** [comment]
honestly yall can do whatever you want. go-fil-markets retrieval client is ONLY used by Lotus. It should probably move directly into the Lotus repo.

everybody else uses FilClient.
