### ISSUE TITLE
Storage Market should not block reading protocol responses

### ISSUE THREAD

**Issue by hannahhoward** [filecoin-project/go-fil-markets#82]
As either a provider or a client in the storage market, I would like to make reading responses from the other party asynchronous, so that my node does not block waiting on the other party

---

In:
- All Read operations in storage market should be handled in protocol handlers
- No more than one read per handler (i.e should read only incoming value from libp2p)
- After processing read, generate event to state machine
- State handlers take it from there

---

Acceptance criteria:
- Create two retrieval deals with different providers on client. Have one provider stop responding. Other deal should proceed

**Comment by mishmosh** [comment]
currently connection stays open until deal is published.
change to be made: go ahead and close the connection after receiving intent to accept, do data transfer on a different connection, and add a new query protocol "what's the state of my deal?". if no, loop(?) with some delay until done.
